# Generated by Django 5.2.3 on 2025-06-14 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="is_admin",
        ),
    ]
