# Generated by Django 5.2.3 on 2025-06-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_remove_member_is_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="loan",
            name="balance_remaining",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="member",
            name="savings_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Initial Savings Balance",
            ),
        ),
    ]
