# Generated by Django 5.2.3 on 2025-06-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_notification_created_at_alter_notification_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
