# Generated by Django 5.2.3 on 2025-06-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_notification_is_read"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="savings_balance",
            field=models.CharField(verbose_name="Initial Savings Balance"),
        ),
    ]
