# Generated by Django 5.2.3 on 2025-06-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_alter_member_savings_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="savings_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Initial Savings Balance",
            ),
        ),
    ]
