# Generated by Django 5.2.3 on 2025-06-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_alter_member_savings_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="savings_balance",
            field=models.IntegerField(),
        ),
    ]
